#═══════[ CORE CONFIG ]═══════✧#
SESSION_ID='Caseyrhodes~ClYySJCT#sO9WPDi0mnr88fqN370rWC3oF-SeTOOZnZztYmU10sA'
PREFIX="."
PUBLIC_MODE='yes'

#═══════[ OWNER DETAILS ]═══════✧#
OWNER_NAME="᚛Ibrahim adams᚜"
OWNER_NUMBER="0791877587"

#═══════[ BOT PROFILE ]═══════✧#
BOT_NAME="BWM-XMD"
BOT_IMAGE="🫠"
STARTING_BOT_MESSAGE='yes'

#═══════[ PRESENCE & AUTOMATION ]═══════✧#
PRESENCE=''
AUTO_READ="yes"
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"

#═══════[ CHAT FEATURES ]═══════✧#
CHATBOT="yes"
AUDIO_CHATBOT="yes"

#═══════[ GROUP SECURITY ]═══════✧#
GROUPANTILINK_REMOVE="yes"
ANTIDELETE_SENT_INBOX="yes"
ANTIDELETE_RECOVER_CONVENTION="yes"

#═══════[ MESSAGE HANDLING ]═══════✧#
STATUS_REACT_EMOJIS="🚀,🌎"
AUTO_REACT="yes"
WELCOME_MESSAGE="yes"
GOODBYE_MESSAGE="yes"

#═══════[ HEROKU CONFIG ]═══════✧#
HEROKU_APP_NAME=
HEROKU_API_KEY=

#═══════[ AUTO REACTIONS ]═══════✧#
AUTO_REACT_STATUS="yes"
AUTO_REPLY_STATUS="yes"
AUTO_REJECT_CALL="no"
AUTO_BIO="no"

#═══════[ MENU DESIGN CONFIG ]═══════✧#
MENU_TOP_LEFT="┌─❖"
MENU_BOT_NAME_LINE="│ "
MENU_BOTTOM_LEFT="└┬❖"
MENU_GREETING_LINE="┌┤ "
MENU_DIVIDER="│└────────┈⳹"
MENU_USER_LINE="│🕵️ "
MENU_DATE_LINE="│📅 "
MENU_TIME_LINE="│⏰ "
MENU_STATS_LINE="│⭐ "
MENU_BOTTOM_DIVIDER="└─────────────┈⳹"
